name: Generate Contribution Snake

on:
  # 每天自動更新一次
  schedule:
    - cron: "0 0 * * *"

  # 可以從 Actions 頁面手動執行
  workflow_dispatch:

  # main 分支更新時也執行
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # 產生貪食蛇 SVG 與 GIF
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ Ekko-001 }}

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 將產生的檔案放到 output 分支
      - name: Push snake files to output branch
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865
        with:
          target_branch: output
          build_dir: dist

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
